#!/bin/sh
#
# Load modules
#

case "$1" in
  start)
	printf "Loading modules...\n"
	/sbin/modprobe matrix-keymap
	/sbin/modprobe tca8418_keypad
	/sbin/modprobe rotary_encoder
	/sbin/modprobe snd
	/sbin/modprobe snd-pcm
	/sbin/modprobe snd-pcm-dmaengine
	/sbin/modprobe snd-hwdep
	/sbin/modprobe snd-timer
	/sbin/modprobe snd-soc-core
	;;
  stop)
	printf "Removing modules...\n"
	/sbin/modprobe -r snd-soc-core
	/sbin/modprobe -r snd-timer
	/sbin/modprobe -r snd-hwdep
	/sbin/modprobe -r snd-pcm-dmaengine
	/sbin/modprobe -r snd-pcm
	/sbin/modprobe -r snd
	/sbin/modprobe -r rotary_encoder
	/sbin/modprobe -r tca8418_keypad
	/sbin/modprobe -r matrix-keymap
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
